<?php

namespace Database\Seeders;

use App\Models\Settings\Setting;
use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Setting::query()->truncate();
        Setting::insert([
            //Site
            [
                'name' => 'Site name',
                'key' => 'site.name',
                'type' => 'general',
                'value' => 'M3rady',
                'value_type' => 'string',
                'description' => 'This is for Site name.',
            ],
            [
                'name' => 'Site description',
                'key' => 'site.description',
                'type' => 'general',
                'value' => 'M3rady',
                'value_type' => 'string',
                'description' => 'This is for Site description.',
            ],
            [
                'name' => 'Site keywords',
                'key' => 'site.keywords',
                'type' => 'general',
                'value' => 'M3rady',
                'value_type' => 'string',
                'description' => 'This is for Site keywords.',
            ],
            [
                'name' => 'Facebook URL',
                'key' => 'facebook.url',
                'type' => 'social',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for Facebook page url',
            ],
            [
                'name' => 'Twitter URL',
                'key' => 'twitter.url',
                'type' => 'social',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for Twitter page url',
            ],
            [
                'name' => 'Instagram URL',
                'key' => 'instagram.url',
                'type' => 'social',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for Instagram page url',
            ],
            [
                'name' => 'LinkedIn URL',
                'key' => 'linkedin.url',
                'type' => 'social',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for LinkedIn page url',
            ],
            [
                'name' => 'Youtube URL',
                'key' => 'youtube.url',
                'type' => 'social',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for Youtube page url',
            ],
            [
                'name' => 'Apple URL',
                'key' => 'apple.url',
                'type' => 'apps',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for Apple url',
            ],
            [
                'name' => 'Android URL',
                'key' => 'android.url',
                'type' => 'apps',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for Android url',
            ],
            [
                'name' => 'Huawei URL',
                'key' => 'huawei.url',
                'type' => 'apps',
                'value' => '#',
                'value_type' => 'string',
                'description' => 'This is for Huawei url',
            ],
            [
                'name' => 'Allow Users To Change Their Name',
                'key' => 'allow.users.change.name',
                'value' => '1',
                'value_type' => 'boolean',
                'type' => 'users',
                'description' => 'Allow Users To Change Their Name or not',
            ],
            [
                'name' => 'Advertisers Pagination Limit',
                'key' => 'advertisers.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'users',
                'description' => 'Advertisers Pagination Limit is how many advertisers sent per page while showing advertisers.',
            ],
            [
                'name' => 'Advertisers Rating Auto Approve',
                'key' => 'advertiser.rate.auto.approve',
                'value' => '1',
                'value_type' => 'boolean',
                'type' => 'users',
                'description' => 'Selects whether auto approve advertisers rating requests or not.',
            ],
            [
                'name' => 'Advertisers Ratings Pagination Limit',
                'key' => 'advertisers.ratings.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'users',
                'description' => 'Advertisers Ratings Pagination Limit is how many Rated/Raters will appear.',
            ],
            [
                'name' => 'User Followings Pagination Limit',
                'key' => 'user.followings.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'users',
                'description' => 'User Followings Pagination Limit is how many followers/followed users will appear.',
            ],
            [
                'name' => 'Offers Pagination Limit',
                'key' => 'offers.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'offers',
                'description' => 'Offers Pagination Limit is how many offers sent per page while showing offers.',
            ],
            [
                'name' => 'Offers Rating Auto Approve',
                'key' => 'offers.rate.auto.approve',
                'value' => '1',
                'value_type' => 'boolean',
                'type' => 'offers',
                'description' => 'Selects whether auto approve offers rating requests or not.',
            ],
            [
                'name' => 'Offers Add Auto Approve',
                'key' => 'offers.default.auto.approve',
                'value' => '1',
                'value_type' => 'boolean',
                'type' => 'offers',
                'description' => 'Selects Whether auto approve adding offer or not.',
            ],
            [
                'name' => 'Reported offers Pagination Limit',
                'key' => 'reported.offers.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'offers',
                'description' => 'Reported offers Pagination Limit is how many offers sent per page while showing reported offers.',
            ],
            [
                'name' => 'Offers Comments Pagination Limit',
                'key' => 'offers.comments.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'offers',
                'description' => 'Offers comments Pagination Limit is how many offers sent per page while showing offers comments.',
            ],
            [
                'name' => 'Reported offers comments Pagination Limit',
                'key' => 'reported.offers.comments.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'offers',
                'description' => 'Reported offers comments Pagination Limit is how many offers sent per page while showing reported offers comments.',
            ],
            [
                'name' => 'Maximum Advertiser Active Offers',
                'key' => 'max.advertiser.active.offers',
                'value' => '1',
                'value_type' => 'integer',
                'type' => 'offers',
                'description' => 'Maximum Advertiser Active Offers is how many active offers at the same time.',
            ],
            [
                'name' => 'Posts Pagination Limit',
                'key' => 'posts.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'Posts Pagination Limit is how many posts sent per page while showing posts.',
            ],
            [
                'name' => 'Reported Posts Pagination Limit',
                'key' => 'reported.posts.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'Reported posts Pagination Limit is how many posts sent per page while showing reported posts.',
            ],
            [
                'name' => 'Hidden Posts Pagination Limit',
                'key' => 'hidden.posts.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'Hidden Posts Pagination Limit is how many posts sent per page while showing hidden posts.',
            ],
            [
                'name' => 'Saved Posts Pagination Limit',
                'key' => 'saved.posts.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'Saved Posts Pagination Limit is how many posts sent per page while showing saved posts.',
            ],
            [
                'name' => 'Subscribed Posts Pagination Limit',
                'key' => 'subscribed.posts.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'Subscribed Posts Pagination Limit is how many posts sent per page while showing subscribed posts.',
            ],
            [
                'name' => 'Posts Comments Pagination Limit',
                'key' => 'comments.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'Posts Comments Pagination Limit is how many comments sent per page while showing posts comments.',
            ],
            [
                'name' => 'Reported Posts Comments Pagination Limit',
                'key' => 'reported.comments.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'Reported posts comments Pagination Limit is how many posts comments sent per page while showing reported posts comments.',
            ],
            [
                'name' => 'Proposals Pagination Limit',
                'key' => 'proposals.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'proposals',
                'description' => 'Proposals Pagination Limit is how many posts sent per page while showing proposals posts.',
            ],
            [
                'name' => 'Reported Proposals Pagination Limit',
                'key' => 'reported.proposals.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'proposals',
                'description' => 'Reported Proposals Pagination Limit is how many proposals sent per page while showing reported proposals.',
            ],
            [
                'name' => 'Username Change Pagination Limit',
                'key' => 'username.change.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'users',
                'description' => 'Username Change Pagination Limit is how many requests sent per page while showing username change requests.',
            ],
            [
                'name' => 'Username Change Limit (in days)',
                'key' => 'username.change.limit',
                'value' => '30',
                'value_type' => 'integer',
                'type' => 'users',
                'description' => 'time limit between username change request and another one.',
            ],
            [
                'name' => 'Chat Channels Pagination Limit',
                'key' => 'chat.channels.pagination.limit',
                'value' => '12',
                'value_type' => 'integer',
                'type' => 'chat',
                'description' => 'Chat Channels Pagination Limit is how many channels sent per page while showing chat channels.',
            ],
            [
                'name' => 'Chat Messages Pagination Limit',
                'key' => 'chat.messages.pagination.limit',
                'value' => '20',
                'value_type' => 'integer',
                'type' => 'chat',
                'description' => 'Chat Messages Pagination Limit is how many messages sent per page while showing chat messages.',
            ],
            [
                'name' => 'Normal Users Max Posts Quantity',
                'key' => 'user.allowed.posts',
                'value' => '30',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'This is to determine max posts quantity allowed for user.',
            ],
            [
                'name' => 'Maximum Video Limit in Seconds',
                'key' => 'max.video.seconds',
                'value' => '30',
                'value_type' => 'integer',
                'type' => 'posts',
                'description' => 'This is to set max video length in seconds allowed for uploaded videos.',
            ],
            [
                'name' => 'Maximum User Categories Interests',
                'key' => 'max.user.categories.interests',
                'value' => '5',
                'value_type' => 'integer',
                'type' => 'users',
                'description' => 'This is to set Maximum User Categories Interests allowed for user.',
            ],
            [
                'name' => 'Maintenance Mode',
                'key' => 'maintenance.mode',
                'value' => '0',
                'value_type' => 'boolean',
                'type' => 'maintenance',
                'description' => 'Enable Maintenance mode or not',
            ],
        ]);
    }
}
