<?php

namespace App\Http\Livewire\Requests\UsernameChange;

use App\Helpers\Admins\AdminLogs;
use App\Models\Requests\ContactForms;
use App\Models\Requests\UsernameRequests;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Jantinnerezo\LivewireAlert\LivewireAlert;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;
use Throwable;

class RequestsUsernameChangeInquiryComponent extends LivewireDatatable
{
    use LivewireAlert;

    public $exportable = true;
    public $hideable = 'select';
    public $model = UsernameRequests::class;
    public string $page_type = 'all';
    public $beforeTableSlot = 'livewire.datatables.selected';
    public bool $has_delete = true;
    public $listeners = ['rerenderDataTable' => 'changeType'];
    public bool $showDeleteModal = false;
    public array $deleteModalTexts;

    public function mount($model = null, $include = [], $exclude = [], $hide = [], $dates = [], $times = [], $searchable = [], $sort = null, $hideHeader = null, $hidePagination = null, $perPage = null, $exportable = false, $hideable = false, $beforeTableSlot = false, $afterTableSlot = false, $params = [])
    {
        parent::mount($model, $include, $exclude, $hide, $dates, $times, $searchable, $sort, $hideHeader, $hidePagination, $perPage, $exportable, $hideable, $beforeTableSlot, $afterTableSlot, $params); // TODO: Change the autogenerated stub
        //set modal texts
        $this->setModalTexts();
    }

    /**
     * set columns to render
     * @return array
     */
    public function columns(): array
    {
        return [
            Column::checkbox(),
            NumberColumn::name('id')
                ->label('#')
                ->filterable()
                ->searchable(),
            Column::callback(['user_type', 'id'], function ($user_type, $id) {
                $type = UsernameRequests::find($id)->user->user_type;
                return $user_type ? __("pages/requests/username-change/index.content.datatable.types.{$type}") : '-';
            })
                ->label(__('pages/requests/username-change/index.content.datatable.user_type'))
                ->filterable()
                ->searchable(),
            Column::callback('user_id', function ($user_id) {
                return $user_id ?: '-';
            })
                ->label(__('pages/requests/username-change/index.content.datatable.user_id'))
                ->filterable()
                ->searchable(),
            Column::callback('id', function ($id) {
                $username = UsernameRequests::findOrFail($id)
                    ->user->name;
                return ucwords($username);
            })
                ->label(__('pages/requests/username-change/index.content.datatable.user_name'))
                ->searchable(),
            Column::name('old_username')
                ->label(__('pages/requests/username-change/index.content.datatable.old_username'))
                ->filterable()
                ->searchable(),
            Column::name('new_username')
                ->label(__('pages/requests/username-change/index.content.datatable.new_username'))
                ->filterable()
                ->searchable(),
            Column::callback('reason', function ($reason) {
                return Str::limit($reason, 40);
            })
                ->label(__('pages/requests/username-change/index.content.datatable.reason'))
                ->filterable()
                ->searchable(),
            Column::callback('status', function ($status) {
                return __("pages/requests/username-change/index.content.datatable.{$status}");
            })
                ->label(__('pages/requests/username-change/index.content.datatable.status'))
                ->filterable([
                    'Approved' => __("pages/requests/username-change/index.content.datatable.approved"),
                    'Declined' => __("pages/requests/username-change/index.content.datatable.declined"),
                    'Pending' => __("pages/requests/username-change/index.content.datatable.pending")
                ])
                ->searchable(),
            Column::callback(['id'], function ($id) {
                return view('admin.pages.requests.change-username.table-actions', ['id' => $id]);
            })
                ->label(__('datatable.actions'))
                ->excludeFromExport()
                ->unsortable(),
        ];
    }

    /**
     * set query to render data
     * @return mixed
     */
    public function builder()
    {
        if ($this->page_type === 'all') {
            return UsernameRequests::selectRaw('*');
        }
        return UsernameRequests::where('status', $this->page_type);
    }


    /**
     * @param $params
     */
    public function changeType($params)
    {
        $this->page_type = $params['status'];
    }

    /**
     * show delete modal
     */
    public function showDeleteModal()
    {
        $this->showDeleteModal = true;
    }

    /**
     * delete Selected data
     */
    public function deleteSelected()
    {
        if (!Auth::guard('admin')->user()->can('requests.username.change')) {
            //send toastr alert with error
            $this->alert('error', __('permissions.insufficient_permissions'), [
                'position' => ((App::currentLocale() === 'ar') ? 'top-start' : 'top-end'),
            ]);
            return null;
        }
        DB::beginTransaction();
        try {
            //get Admins
            $requests = UsernameRequests::query()
                ->whereIn('id', $this->selected)
                ->get();

            parent::delete($this->selected);

            //reset selected to empty
            $this->selected = [];

            //send toastr alert with success
            $this->alert('success', __('toastr.delete'), [
                'position' => ((App::currentLocale() === 'ar') ? 'top-start' : 'top-end'),
            ]);

            //hide modal
            $this->showDeleteModal = false;

            //add log
            AdminLogs::log('delete', 'username-requests', [
                'requests' => $requests
            ], "Delete: username-requests");

        } catch (Throwable $e) {
            //rollback changes
            DB::rollBack();

            //send toastr alert with error
            $this->alert('error', __('toastr.error'), [
                'position' => ((App::currentLocale() === 'ar') ? 'top-start' : 'top-end'),
                'text' => $e->getMessage(),
            ]);

            return null;
        }
        //commit changes
        DB::commit();
    }


    /**
     * set Modal Texts
     */
    public function setModalTexts()
    {
        $this->deleteModalTexts = [
            'title' => __('pages/requests/username-change/inquiry.modal.delete.title'),
            'content' => __('pages/requests/username-change/inquiry.modal.delete.content'),
            'cancel' => __('pages/requests/username-change/inquiry.modal.delete.cancel'),
            'submit' => __('pages/requests/username-change/inquiry.modal.delete.submit'),
        ];
    }
}
